name: word-golf
services:
  - name: dockerbuild
    github:
      repo: rkique/word.golf
      branch: main
    dockerfile_path: Dockerfile
    build_command: ""
    run_command: "python app.py"
    envs:
      - key: GITHUB_TOKEN
        scope: BUILD_AND_RUNTIME
        value: ${GITHUB_TOKEN}
    build_envs:
      - key: GITHUB_TOKEN
        scope: BUILD
        value: ${GITHUB_TOKEN}
        