"""add fake gamestates

Revision ID: 1448bda198e1
Revises: 3b26e0cf8d63
Create Date: 2025-07-23 09:46:29.972367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1448bda198e1'
down_revision = '3b26e0cf8d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fake_game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_date', sa.Date(), nullable=True),
    sa.Column('selected_words', mysql.JSON(), nullable=True),
    sa.Column('jumpsA', mysql.JSON(), nullable=True),
    sa.Column('total_jumps', sa.Integer(), nullable=True),
    sa.Column('results', mysql.JSON(), nullable=True),
    sa.Column('prompt_idx', sa.Integer(), nullable=True),
    sa.Column('current_jumps', sa.Integer(), nullable=True),
    sa.Column('prompts', mysql.JSON(), nullable=True),
    sa.Column('start_target_idxs', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'current_date', name='user_date_uc')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('fake_game_state')
    # ### end Alembic commands ###
