"""added mutable lists

Revision ID: 312039106c28
Revises: a747e13642a2
Create Date: 2025-06-25 11:07:38.160946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '312039106c28'
down_revision = 'a747e13642a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.alter_column('jumpsA',
            existing_type=mysql.JSON(),
            type_=sa.JSON(),
            existing_nullable=True)
        batch_op.alter_column('selected_words',
            existing_type=mysql.JSON(),
            type_=sa.JSON(),
            existing_nullable=True)
        batch_op.alter_column('results',
            existing_type=mysql.JSON(),
            type_=sa.JSON(),
            existing_nullable=True)
        batch_op.alter_column('prompts',
            existing_type=mysql.JSON(),
            type_=sa.JSON(),
            existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.alter_column('prompts',
            existing_type=sa.JSON(),
            type_=mysql.JSON(),
            existing_nullable=True)
        batch_op.alter_column('results',
            existing_type=sa.JSON(),
            type_=mysql.JSON(),
            existing_nullable=True)
        batch_op.alter_column('selected_words',
            existing_type=sa.JSON(),
            type_=mysql.JSON(),
            existing_nullable=True)
        batch_op.alter_column('jumpsA',
            existing_type=sa.JSON(),
            type_=mysql.JSON(),
            existing_nullable=True)

    # ### end Alembic commands ###