"""Add start_target_idxs to GameState

Revision ID: 3b26e0cf8d63
Revises: 312039106c28
Create Date: 2025-07-07 11:33:55.691287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b26e0cf8d63'
down_revision = '312039106c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_target_idxs', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.drop_column('start_target_idxs')

    # ### end Alembic commands ###
