"""edit_user_gamestate

Revision ID: 53525faf14f7
Revises: b3c08def7a52
Create Date: 2025-08-01 09:58:51.163160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53525faf14f7'
down_revision = 'b3c08def7a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user_constructed_gamestate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.drop_column('user_player_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_constructed_gamestate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_player_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
