"""create_prompts_migration

Revision ID: 6e29c4e79c02
Revises: 1448bda198e1
Create Date: 2025-07-28 11:01:15.464036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e29c4e79c02'
down_revision = '1448bda198e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_constructed_gamestate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_creator_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=36), nullable=True),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('user_player_id', sa.String(length=36), nullable=False),
    sa.Column('current_date', sa.Date(), nullable=True),
    sa.Column('selected_words', mysql.JSON(), nullable=True),
    sa.Column('jumpsA', mysql.JSON(), nullable=True),
    sa.Column('total_jumps', sa.Integer(), nullable=True),
    sa.Column('results', mysql.JSON(), nullable=True),
    sa.Column('prompt_idx', sa.Integer(), nullable=True),
    sa.Column('current_jumps', sa.Integer(), nullable=True),
    sa.Column('prompts', mysql.JSON(), nullable=True),
    sa.Column('start_target_idxs', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_constructed_gamestate')
    # ### end Alembic commands ###
