"""added prompts to gamestate

Revision ID: a747e13642a2
Revises: d6deacc50a91
Create Date: 2025-06-23 15:36:34.593146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a747e13642a2'
down_revision = 'd6deacc50a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompts', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.drop_column('prompts')

    # ### end Alembic commands ###
