"""enforce_selected_word_list

Revision ID: b3c08def7a52
Revises: 6e29c4e79c02
Create Date: 2025-07-28 12:01:21.072343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3c08def7a52'
down_revision = '6e29c4e79c02'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE game_state SET selected_words = JSON_ARRAY() WHERE selected_words IS NULL")
    )
    conn.execute(
        sa.text("UPDATE fake_game_state SET selected_words = JSON_ARRAY() WHERE selected_words IS NULL")
    )
    conn.execute(
        sa.text("UPDATE user_constructed_gamestate SET selected_words = JSON_ARRAY() WHERE selected_words IS NULL")
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fake_game_state', schema=None) as batch_op:
        batch_op.alter_column('selected_words',
               existing_type=mysql.JSON(),
               nullable=False)

    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.alter_column('selected_words',
               existing_type=mysql.JSON(),
               nullable=False)


    with op.batch_alter_table('user_constructed_gamestate', schema=None) as batch_op:
        batch_op.alter_column('selected_words',
               existing_type=mysql.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_constructed_gamestate', schema=None) as batch_op:
        batch_op.alter_column('selected_words',
               existing_type=mysql.JSON(),
               nullable=True)

    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.alter_column('selected_words',
               existing_type=mysql.JSON(),
               nullable=True)

    with op.batch_alter_table('fake_game_state', schema=None) as batch_op:
        batch_op.alter_column('selected_words',
               existing_type=mysql.JSON(),
               nullable=True)

    # ### end Alembic commands ###