"""added gamestate func

Revision ID: d6deacc50a91
Revises: df9f34e7dae1
Create Date: 2025-06-23 12:41:12.561996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6deacc50a91'
down_revision = 'df9f34e7dae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.drop_constraint('game_state_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('user_date_uc', type_='unique')
        batch_op.drop_column('date')
        batch_op.create_unique_constraint('user_date_uc', ['user_id', 'current_date'])
        batch_op.create_foreign_key('game_state_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.drop_constraint('user_date_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('user_date_uc'), ['user_id', 'date'])
        batch_op.drop_column(sa.Column('current_date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
